language: node_js
node_js: node
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: lgkGkcPcCupoLk//UuBarCvgih2O0MidSlq+SYHV0ihCnwYg8l4S4DTiKBhbc9ShLwt2mWiBCYdKY7eFEQU4WgEDhD9Z3kxOJYOsKgdkap2u6lj4V35GrTIub9vX8bjHMLj4RxN39ti6bB88zn4gFZfjdY9R79x82m8oroqr2D6wyu9PHfqPw2MCwhuP/YNKPVnq9e8odbguqlLAiOH0RAwxtDcRbXkyjfjue8lzk/ctAR/sUXR4UbZWkROMjqT2jQ5OtwatjVBak/1PGLA5417a2rWIMDkCY4+VBLEAJSxOFHIL/uMZnRIkq94sUSo3vM7B75SIgaI5d0btfbKRkHsf06KeMY4KSPon/5sH3srMCx++WPpXhUEDVFo9DdDEYjTigVbexX6OTuHaERQqRA9Q/r3pb5sRMZ1U9l7u28vUGEbXP67tfLvlk/7BhbvR1ul+7ozZ4wJ8ndPtMzQ5aC7X0rU2Gtz5qF8mJR1S+KXvQZHZillb5mWb0dd129gHQO31SmCPo/Wv2zafk3wZUNcd+yk8eUjZYTx6YnWwazY/Vof+UVLBi7cPshr33k8G1cMrmBc4rQnQmpa/bTiOSa1oRcE+wV777amS+0b/cz54gofx58c67fSczIwf6Nfix1FhuI7Pn/TKr1VyZZCb6gmb5fps5+6JReM9Q+YmM00=
  app: warehouse-caddy
  on:
    repo: adrianasu/warehouse-inventory-client
