language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: SZtTs6iugUonUDYoHgSc3RGNxF/Ttb/HgmJE1Qz/cddOxiH2Dwwlb67SWpWoVbKsjE3HH3KSmAFbpxAxBCWTulqjwO6FMdJ5VkMAhMv6HcY3bgVRYYarc28bYdFj/gSvS/cVOcfboNC/XUxbP5kpmcdQpW6HbMHjoGr0XEAr9xGXzgl6E8ApqOohwfbpkAbzDHeI1XwuT9osfsoFPc9eN54qrcSXI+PZaFIAHCxVhZHKxEfJX5pp70Hne93W9pQg0w50D9Wy/RhdEbI58RkB/R+npqPyXARLnxrXQjpSZLQ3akhnum/PoZ5UO7tEis64VS919OWsbKm5IQl2EAAkrw8wqBX9nuJhJT6LwbM5wGn+jtrmBQngDOE46eJ3akxTTHazzFAvcd2iOxV9uDpFtUqtnrDlfOa2vzzCc3M4EEvPsOni8Gh6+ldIk9hp/qGeCmdhRKxXLnV+pDo7PYUR5zYyctyNbQNrLlE+/Vjp5wKDabz5phws5yzepjwkGqnhN3MV7t2SdoflZPNG9ufz1SF7TSw5TxXjUad2y57ExPlT09Th4qJkUpIbBsyzzxxKEUx8hK2edQM7tQElBwrrIPPRSs95fDiaVN2xXhC/9LlsJkV31ruAQERdK6Z+25rIR83ptp8wwvIwxxj6/BfQRDrJ9VaJW4mFDzAduUtHDnI=
  app: tranquil-coast-85544
  on:
    repo: adrianasu/warehouse-inventory-client
