//  "@fortawesome/free-solid-svg-icons": "^5.6.3",
//  "@fortawesome/pro-light-svg-icons": "^5.7.0",
//  "@fortawesome/pro-regular-svg-icons": "^5.7.0",
//  "@fortawesome/pro-solid-svg-icons": "^5.7.0",

import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faBan,
    faCheckCircle,
    faHome,
    faLightbulb,
    faList,
    faPrint,
    faQuestionCircle,
    faSearch,
    faStar,
    faTimes,
    faTimesCircle,
    faUserCircle,
    faWarehouse,
} from '@fortawesome/free-solid-svg-icons';

import {
    faBoxes,
    faEllipsisV,
    faFilePlus,
    faHeartbeat,
    faIndustryAlt,
    faTachometerSlowest, 
    faToolbox,
    faUser,
    faUsers,
    faWrench,
} from '@fortawesome/pro-regular-svg-icons';

import {
    faArrowAltCircleLeft,
    faCartPlus,
    faChartBar,
    faCheck,
    faDoorOpen,
    faFileUser,
    faInboxIn,
    faInboxOut,
    faInfoCircle,
    faInventory,
    faListAlt,
    faShieldCheck,
    faSignInAlt,
    faUserPlus,
} from '@fortawesome/pro-solid-svg-icons';

import {
    faUserHardHat, 
} from '@fortawesome/pro-light-svg-icons';

library.add(
    faArrowAltCircleLeft,
    faBan, 
    faBoxes,
    faCartPlus,
    faChartBar,
    faCheck,
    faCheckCircle, 
    faDoorOpen,
    faEllipsisV,
    faFilePlus,
    faFileUser,
    faHeartbeat,
    faHome,
    faInboxIn,
    faInboxOut,
    faIndustryAlt,
    faInfoCircle,
    faInventory,
    faLightbulb, 
    faList,
    faListAlt,
    faPrint, 
    faQuestionCircle, 
    faSearch,
    faShieldCheck,
    faSignInAlt,
    faStar, 
    faTachometerSlowest,
    faTimes, 
    faTimesCircle, 
    faToolbox,
    faUser,
    faUserCircle, 
    faUserHardHat,
    faUserPlus,
    faUsers,
    faWarehouse, 
    faWrench,
);